version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache1
    build:
      context: ./phpDir
      dockerfile: Dockerfile
    depends_on:
      - db1
    volumes:
      - ./phpDir/src:/var/www/html/
    ports:
      - 8090:80
  db1:
    platform: linux/x86_64
    container_name: db1
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lionPass
      MYSQL_DATABASE: lionDB
      MYSQL_USER: lionUser
      MYSQL_PASSWORD: lionPass
    ports:
      - "9990:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9090:80"
    restart: always
    environment:
      PMA_HOST: db1
    depends_on:
      - db1
